#!/usr/bin/python3
if __name__ == "__main__":
    from calculator_1 import add, sub, mul, div
    import sys
    size = len(sys.argv)
    if size < 4:
       print("Usage: ./100-my_calculator.py <a> <operator> <b>")
       sys.exit(1)
